alias clip='xclip -selection clipboard'
alias cp='cp -i'
alias df='df -h'
alias egrep='egrep --colour=auto'
alias fgrep='fgrep --colour=auto'
alias free='free -m'
alias grep='grep --colour=auto'
alias grm='source ~/.grm/grm.sh'
alias gtt='git init && git commit --allow-empty -m '\''init!!'\'''
alias ll='lsd -lA'
alias ls='ls --color=auto'
alias more='less'
alias np='nano -w PKGBUILD'
alias sypo='systemctl poweroff'
alias syre='systemctl reboot'
